=== dougdonohoe/ddphotos-app/code/engine/src/main/resources/config/xml-schema/appdef.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.donohoedigital.com"
            xmlns="http://www.donohoedigital.com"
            xmlns:dd="http://www.donohoedigital.com"
            elementFormDefault="qualified">

    <xsd:include schemaLocation="classpath:config/xml-schema/data-elements.xsd"/>

<!-- ********************************** -->
<!-- DEFINES TYPES                      -->
<!-- ********************************** -->

	<xsd:complexType name="paramlist">
    	<xsd:sequence>
	    	<xsd:element name="strvalue" type="string" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="boolvalue" type="boolean" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="intvalue" type="integer" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="dblvalue" type="double" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
		<xsd:attribute name="name" type="basicname" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="param">
		<xsd:attribute name="name" type="basicname" use="required"/>
		<xsd:attribute name="strvalue" type="string" use="optional"/>
		<xsd:attribute name="boolvalue" type="boolean" use="optional"/>
		<xsd:attribute name="intvalue" type="integer" use="optional"/>
		<xsd:attribute name="dblvalue" type="double" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="phase">
    	<xsd:sequence>
	    	<xsd:element name="param" type="param" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="paramlist" type="paramlist" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
		<xsd:attribute name="name" type="basicname" use="required"/>
		<xsd:attribute name="class" type="classname" use="optional"/>
		<xsd:attribute name="extends" type="basicname" use="optional"/>
		<xsd:attribute name="cache" type="boolean" use="optional"/>
		<xsd:attribute name="history" type="boolean" use="optional"/>
		<xsd:attribute name="transient" type="boolean" use="optional"/>
		<xsd:attribute name="window" type="basicname" use="optional"/>
	</xsd:complexType>

<!-- ********************************** -->
<!-- OBJECTS DEFINITION (FOR XML DOCS)  -->
<!-- ********************************** -->

    <xsd:element name="APPDEF">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element name="startphase" type="basicname" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="phase" type="phase" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>

		<!-- define phase name is a key and must be unique -->
		<xsd:key name="PHASE-KEY">
			<xsd:selector xpath="dd:phase"/>
			<xsd:field xpath="@name"/>
		</xsd:key> 

		<!-- define startphase name must ref valid phase -->
		<xsd:keyref name="START-PHASE-REF" refer="PHASE-KEY">
            <xsd:selector xpath="dd:APPDEF"/>
            <xsd:field xpath="startphase"/>
        </xsd:keyref>

		<!-- define extends name must ref valid phase -->
		<xsd:keyref name="EXTENDS-PHASE-REF" refer="PHASE-KEY">
            <xsd:selector xpath="dd:phase"/>
            <xsd:field xpath="extends"/>
        </xsd:keyref>

    </xsd:element>
</xsd:schema>

=== dougdonohoe/ddphotos-app/code/photos/src/main/resources/config/ddphotos/appdef.xml
<?xml version="1.0"?>
<APPDEF xmlns="http://www.donohoedigital.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.donohoedigital.com ../../../../../../engine/src/main/resources/config/xml-schema/appdef.xsd">

    <!--              -->
    <!-- START PHASE  -->
    <!--              -->

    <startphase>StartMenu</startphase>

    <!--         -->
    <!-- PHASES  -->
    <!--         -->

    <phase name="StartMenu" class="com.donohoedigital.ddphotos.PhotosBasePhase" history="true"/>

    <phase name="Help" class="com.donohoedigital.app.engine.Help" history="true" window="help" cache="true">
        <param name="window-title" strvalue="msg.windowtitle.help"/>
        <param name="window-width" intvalue="940"/>
        <param name="window-height" intvalue="700"/>
        <param name="window-multi" boolvalue="false"/>
        <param name="window-resize" boolvalue="true"/>
        <param name="style" strvalue="Help"/>
        <param name="bevel-style" strvalue=""/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-style" strvalue="Help"/>
    </phase>

    <phase name="Support" class="com.donohoedigital.app.engine.Support" history="true" window="support" cache="true">
        <param name="window-title" strvalue="msg.windowtitle.support"/>
        <param name="window-width" intvalue="1600"/>
        <param name="window-height" intvalue="800"/>
        <param name="window-multi" boolvalue="false"/>
        <param name="window-resize" boolvalue="true"/>
        <param name="style" strvalue="Support"/>
        <param name="help-style" strvalue="PhotosHelp"/>
        <param name="bevel-style" strvalue=""/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-style" strvalue="Support"/>
    </phase>

    <phase name="PhotogenEditor" class="com.donohoedigital.ddphotos.PhotogenEditorPhase" history="false" window="photogen-editor" cache="false">
        <param name="window-title" strvalue="msg.windowtitle.PhotogenEditor"/>
        <param name="window-width" intvalue="1200"/>
        <param name="window-height" intvalue="650"/>
        <param name="window-multi" boolvalue="true"/>
        <param name="window-resize" boolvalue="true"/>
        <param name="style" strvalue="Options"/>
        <param name="bevel-style" strvalue=""/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-style" strvalue="Options"/>
    </phase>

    <phase name="CssEditor" class="com.donohoedigital.ddphotos.CssEditorPhase" history="false" window="css-editor" cache="false">
        <param name="window-title" strvalue="msg.windowtitle.CssEditor"/>
        <param name="window-width" intvalue="900"/>
        <param name="window-height" intvalue="650"/>
        <param name="window-multi" boolvalue="true"/>
        <param name="window-resize" boolvalue="true"/>
        <param name="style" strvalue="TextEditor"/>
        <param name="bevel-style" strvalue=""/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-style" strvalue="Options"/>
    </phase>

    <phase name="SiteEnvEditor" class="com.donohoedigital.ddphotos.SiteEnvEditorPhase" history="false" window="site-env-editor" cache="false">
        <param name="window-title" strvalue="msg.windowtitle.SiteEnvEditor"/>
        <param name="window-width" intvalue="900"/>
        <param name="window-height" intvalue="650"/>
        <param name="window-multi" boolvalue="true"/>
        <param name="window-resize" boolvalue="true"/>
        <param name="style" strvalue="TextEditor"/>
        <param name="bevel-style" strvalue=""/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-style" strvalue="Options"/>
    </phase>

    <phase name="SiteDialog" class="com.donohoedigital.ddphotos.SiteDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.SiteDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <phase name="AlbumDialog" class="com.donohoedigital.ddphotos.AlbumDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.AddAlbumDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <!-- The sync credentials dialogs, one per provider, sharing a class.  dialog-maxwidth is off
         (0) because the dialog sizes itself to fit a whole API key, which can be wider than the
         750 default. -->
    <phase name="ImmichCredentialsDialog" class="com.donohoedigital.ddphotos.SyncCredentialsDialog" transient="true">
        <param name="provider" strvalue="immich"/>
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-maxwidth" intvalue="0"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.ImmichCredentialsDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <phase name="PhotoPrismCredentialsDialog" class="com.donohoedigital.ddphotos.SyncCredentialsDialog" transient="true">
        <param name="provider" strvalue="photoprism"/>
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-maxwidth" intvalue="0"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.PhotoPrismCredentialsDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <!-- dialog-maxwidth is off (0) because the dialog sizes itself to fit the cache path,
         which can be wider than the 750 default. -->
    <phase name="ThumbnailCacheDialog" class="com.donohoedigital.ddphotos.ThumbnailCacheDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-maxwidth" intvalue="0"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.ThumbnailCacheDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="okay"/>
        <param name="default-button" strvalue="okay"/>
        <paramlist name="buttons">
            <strvalue>okay</strvalue>
        </paramlist>
    </phase>

    <phase name="BaseDialog" class="com.donohoedigital.ddphotos.BaseDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.AddBaseDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <!-- The photo chooser sizes itself from the app window, so dialog-maxwidth is turned off
         (0) to keep DialogBackground from squeezing it back down to the 750 default. -->
    <phase name="PhotoChooser" class="com.donohoedigital.ddphotos.PhotoChooserDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-maxwidth" intvalue="0"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.PhotoChooser"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
